local AddOnName, AddOn

describe("AddOn", function()
    setup(function()
        AddOnName, AddOn = loadfile("Test/TestSetup.lua")(true)
    end)
    teardown(function()
        After()
    end)

    describe("is", function()
        it("loaded", function()
            assert(AddOn.Constants.name == AddOnName)
        end)
        it("initalized", function()
            AddOnLoaded(AddOnName, false)
        end)
        it("enabled", function()
            AddOnLoaded(AddOnName, true)
        end)
        it("able to handle player entering world", function()
            PlayerEnteredWorld()
        end)
    end)
end)