local AddOnName, AddOn

describe("AddOn", function()
    setup(function()
        AddOnName, AddOn = loadfile("Test/TestSetup.lua")(true)
    end)
    teardown(function()
        After()
    end)

    describe("is", function()
        it("loaded", function()
            assert(AddOn.Constants.name == AddOnName)
        end)
        it("able to use api compatibility globals", function()
            assert.is_function(GuildRoster)
            assert.is_function(GetNumGuildMembers)
            assert.is_function(GetGuildRosterInfo)
            assert.is_function(GetGuildInfo)
            assert.is_function(GetGuildInfoText)
        end)
        it("initalized", function()
            AddOnLoaded(AddOnName, false)
        end)
        it("enabled", function()
            AddOnLoaded(AddOnName, true)
        end)
        it("able to handle player entering world", function()
            PlayerEnteredWorld()
        end)
    end)
end)
