local AddOn, Util, Versioned, SemanticVersion, Date

describe("Versioned", function()
	setup(function()
		_, AddOn = loadfile("Test/TestSetup.lua")(true, 'Models_Versioned')
		local p = AddOn.Package('Models')
		Versioned, SemanticVersion, Date = p.Versioned, p.SemanticVersion, p.Date
		Util = AddOn:GetLibrary('Util')
	end)

	teardown(function()
		After()
	end)

	describe("creation", function()
		it("default", function ()
			local v = Versioned()
			assert(v)
			assert(v.version)
			assert.equal(v.version, SemanticVersion(1, 0))
			assert(v.revision)
			assert.equal(v.revision, v:RevisionAsDate().time)
		end)
		it("specific version", function ()
			local v = Versioned("1.0.1")
			assert(v)
			assert(v.version)
			assert.equal(v.version, SemanticVersion(1, 0, 1))
			assert(v.revision)
			assert.equal(v.revision, v:RevisionAsDate().time)
			print(Util.Objects.ToString(v:toTable()))
		end)
		it("supports triggers", function()
			local v = Versioned("1.0.1", "one", "two")
			assert(v:TriggersNewRevision("one"))
			assert(v:TriggersNewRevision("two"))
			assert(not v:TriggersNewRevision("three"))
		end)
	end)
end)