local AddOn, Util, Versioned, SemanticVersion, Date, Class

describe("Versioned", function()
	setup(function()
		_, AddOn = loadfile("Test/TestSetup.lua")(true, 'Models_Versioned')
		local p = AddOn.Package('Models')
		Versioned, SemanticVersion, Date = p.Versioned, p.SemanticVersion, p.Date
		Util, Class = AddOn:GetLibrary('Util'), AddOn:GetLibrary('Class')
	end)

	teardown(function()
		After()
	end)

	describe("creation", function()
		it("default", function ()
			local v = Versioned()
			assert(v)
			assert(v.version)
			assert.equal(v.version, SemanticVersion(1, 0))
			assert(v.revision)
			assert.equal(v.revision, v:RevisionAsDate().time)
		end)
		it("specific version", function ()
			local v = Versioned("1.0.1")
			assert(v)
			assert(v.version)
			assert.equal(v.version, SemanticVersion(1, 0, 1))
			assert(v.revision)
			assert.equal(v.revision, v:RevisionAsDate().time)
			print(Util.Objects.ToString(v:toTable()))
		end)
		it("supports triggers", function()
			local Test = Class('Test', Versioned)
			Test.static:AddTriggers( "one", "two")

			function Test:initialize()
				Versioned.initialize(self, "1.0.1")
			end

			local v = Test()
			assert(v:TriggersNewRevision("one"))
			assert(v:TriggersNewRevision("two"))
			assert(not v:TriggersNewRevision("three"))
		end)
	end)
end)