local Encounter, Util

describe("LibEncounter(Localized)", function()
	setup(function()
		loadfile("Test/TestSetup.lua")(false, 'LibEncounter')
		SetLocale("frFR")
		loadfile("Libs/LibEncounter-1.1/Test/BaseTest.lua")()
		LoadDependencies()
		ParseXmlAndLoad('Libs/LibEncounter-1.1/LibEncounter-1.1.xml')
		ConfigureLogging()
		Encounter = LibStub('LibEncounter-1.1', true)
		Util = LibStub('LibUtil-1.2', true)
	end)
	teardown(function()
		After()
	end)
    describe("map ids", function()
        it("resolved from map names", function()
            assert.equal(409, Encounter:GetMapId('Cœur du Magma'))
        end)
    end)
end)